name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependencias
        run: npm install

      - name: Executar Testes Unitarios
        run: npm test

  deploy:
    name: Continuous Delivery (CD)
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Validar Build e Entrega
        run: echo "Build e entrega validados com sucesso no pipeline de CD!"